pipeline {
    agent any
    parameters {  // Se declaran parametros
        string(name: 'PROCESO', defaultValue: 'bash', description: 'Ingrese nombr de proceso')
    }
    stages {
        stage('Execution') {
            steps {
                script {
                    sh "./script.sh $PROCESO"            
                }
            }
        }
    }
}